export const testimonials = [
	{
		id: 1,
		name: "Sarah M.",
		location: "Kreuzberg, Berlin",
		rating: 5,
		text: "The fastest food delivery I've experienced in Berlin! My order arrived hot and fresh, exactly as promised. The app is so easy to use, and the delivery updates are spot on.",
		image: "https://randomuser.me/api/portraits/women/1.jpg",
		role: "Regular Customer",
	},
	{
		id: 2,
		name: "Marcus K.",
		location: "Mitte, Berlin",
		rating: 5,
		text: "As a restaurant owner, partnering with this platform has significantly increased our orders. Their system is reliable, and the support team is always helpful.",
		image: "https://randomuser.me/api/portraits/men/2.jpg",
		role: "Restaurant Partner",
	},
	{
		id: 3,
		name: "Lisa W.",
		location: "Prenzlauer Berg, Berlin",
		rating: 5,
		text: "I love the variety of restaurants available. From traditional German cuisine to international dishes, everything is just a few clicks away. The special offers are great too!",
		image: "https://randomuser.me/api/portraits/women/3.jpg",
		role: "Food Enthusiast",
	},
	{
		id: 4,
		name: "Thomas R.",
		location: "Friedrichshain, Berlin",
		rating: 5,
		text: "Working as a delivery partner has been fantastic. The app is user-friendly, and the earning potential is great. It's the perfect flexible job for students like me.",
		image: "https://randomuser.me/api/portraits/men/4.jpg",
		role: "Delivery Partner",
	},
	{
		id: 5,
		name: "Emma H.",
		location: "Charlottenburg, Berlin",
		rating: 5,
		text: "As someone with dietary restrictions, I appreciate how easy it is to filter restaurants and dishes. The allergen information is clearly displayed, making ordering worry-free.",
		image: "https://randomuser.me/api/portraits/women/5.jpg",
		role: "Health-Conscious Customer",
	},
	{
		id: 6,
		name: "Jan B.",
		location: "Schöneberg, Berlin",
		rating: 5,
		text: "My small café has seen a 40% increase in lunch orders since joining the platform. The commission rates are fair, and the tablet system they provided works flawlessly.",
		image: "https://randomuser.me/api/portraits/men/6.jpg",
		role: "Restaurant Partner",
	},
	{
		id: 7,
		name: "Nina S.",
		location: "Neukölln, Berlin",
		rating: 5,
		text: "The loyalty program is fantastic! I've earned so many rewards points from my regular orders. The customer service team is also incredibly responsive when needed.",
		image: "https://randomuser.me/api/portraits/women/7.jpg",
		role: "Regular Customer",
	},
	{
		id: 8,
		name: "David P.",
		location: "Wedding, Berlin",
		rating: 5,
		text: "Being a delivery partner fits perfectly around my main job. The real-time heat maps help me maximize my earnings, and the weekly payment system is very reliable.",
		image: "https://randomuser.me/api/portraits/men/8.jpg",
		role: "Delivery Partner",
	},
	{
		id: 9,
		name: "Maria F.",
		location: "Moabit, Berlin",
		rating: 5,
		text: "The group ordering feature is a lifesaver for office lunches! Everyone can choose their own meals, and everything arrives together. It makes organizing team lunches so much easier.",
		image: "https://randomuser.me/api/portraits/women/9.jpg",
		role: "Corporate Customer",
	},
	{
		id: 10,
		name: "Oliver K.",
		location: "Pankow, Berlin",
		rating: 5,
		text: "Our restaurant's online presence has grown significantly since joining. The platform's marketing tools and analytics help us understand our customers better and optimize our menu.",
		image: "https://randomuser.me/api/portraits/men/10.jpg",
		role: "Restaurant Partner",
	},
];
